name: 🚀 Suggest an Icon
title: '[CREATED ICON] Skill Name'
description: Submit an icon you made to be added to the list!
labels: 'icon submission'
body:

# skill name block
- type: input
  id: skill-name
  attributes:
    label: Skill Name
    description: "The name of the skill you're suggesting. Feel free to suggest more than one!"
    placeholder: "VS Code"
  validations:
    required: true

# reason to add block
- type: textarea
  id: reason
  attributes:
    label: Why?
    description: "Why we should add the skill(s) to the project."
    placeholder: "It's popular for web development..."
  validations:
    required: true

# reference image block
- type: textarea
  id: icon
  attributes:
    label: Completed icon(s)
    description: "Your completed SVG icon(s)"
    placeholder: "Feel free to drag and drop the files here."
  validations:
    required: true
